# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'chatty_chatbot' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for chatty_chatbot
  pod 'AWSLex'
  pod 'AWSMobileClient'

end
